### ISSUE TITLE
Fail to compile, when installing biocLitee

### ISSUE THREAD

**Issue by sengoku93** [Bioconductor/BiocInstaller#3]
Hi,

I am having trouble figuring out why I get an error when installing/updating biocLite. Any advice is appreciated. Thank you!

![screenshot 2018-03-13 20 11 43](https://user-images.githubusercontent.com/37084775/37376496-e5d490ae-26fa-11e8-84c0-dc24de615906.png)

**Comment by mtmorgan** [comment]
This is an error in the installation of the Rcpp package, rather than with `biocLite()`. It looks like the problem is related to your installation of the R tools required to build packages containing source (C / C++) code on the Mac. Simplify the problem

```
install.packages("Rcpp")
```

Ensure that the [macOS tools][1] are installed correctly.

Ask for further support on the  [R-sig-mac][2] mailing list.

[1]: http://r.research.att.com/tools/
[2]: https://stat.ethz.ch/mailman/listinfo/r-sig-mac
